services:
  form-app:
    build: .
    image: santiagvs/tomcat-formulario:latest
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    volumes:
      - ./target/formulario.war:/usr/local/tomcat/webapps/formulario.war
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    deploy:
      replicas: 3
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_r_pass
      MYSQL_DATABASE: backend
    volumes:
      - mysql_data:/var/lib/mysql
      - ./aulaback.sql:/docker-entrypoint-initdb.d/aulaback.sql
    secrets:
      - mysql_r_pass

volumes:
  mysql_data:

secrets:
  mysql_r_pass:
    file: ./secrets/mysql_root_password.txt
